# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6c1b527b1f6c5126f8928a55b7c58614"
name = "discount-app"
handle = "discount-app-219"
application_url = "https://nav-serial-blues-plates.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://nav-serial-blues-plates.trycloudflare.com/auth/callback", "https://nav-serial-blues-plates.trycloudflare.com/auth/shopify/callback", "https://nav-serial-blues-plates.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
